# Generated by Django 3.2.25 on 2026-07-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Téléphone')),
                ('photo_profil', models.CharField(blank=True, max_length=255, null=True, verbose_name='Photo de profil')),
                ('promo', models.CharField(max_length=10, verbose_name='Promotion')),
                ('filiere', models.CharField(max_length=100, verbose_name='Filière')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('competences', models.TextField(verbose_name='Compétences (séparées par des virgules (ex: python, bd, algo))')),
                ('disponibilites', models.TextField(verbose_name='Disponibilités (ex: Lundi 14h-16h)')),
                ('format_mentorat', models.CharField(choices=[('presentiel', 'Présentiel'), ('en_ligne', 'En ligne'), ('les_deux', 'Les deux')], default='les_deux', max_length=30, verbose_name='Format de mentorat')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentors',
                'db_table': 'ifri_mentorLink_rattrapage',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
