# Generated by Django 3.2.25 on 2026-07-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/', verbose_name='Photo de profil'),
        ),
    ]
